version: '2'
services:
  nako:
    container_name: stratis-nako
    networks: 
        nakonet:
            ipv4_address: 172.16.11.100
    image: coinvault/nako
    command: stratis
    ports: 
        - 80:9000
        - 443:9000
        - 9030:9000
    depends_on:
        - mongo
        - client
  client:
    container_name: stratis-client
    networks: 
        nakonet:
            ipv4_address: 172.16.11.101
    image: stratisplatform/fullnode:StratisMain
    command: ["dotnet", "run", "--", "-server=1", "-rpcallowip=172.16.11.100", "-rpcbind=172.16.11.101", "-rpcport=5000", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword", "-rpcthreads=300", "-txindex=1"]
    ports: 
        - 5030:5000
        - 16178:16178
  mongo:
    container_name: stratis-mongo
    networks: 
        nakonet:
            ipv4_address: 172.16.11.102
    image: mongo:3.2
networks:
  nakonet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.11.0/24